title: Ricardo's Kitchen
description: Welcome to my blog. I'm <b>Ricardo Costa</b>, also known as <i>astreuw</i>. I'm a computer engineering student with a passion for computers, chemistry and art. I enjoy creating things and sharing knowledge with others. Currently learning German and trying to understand some math concepts.
baseurl: ""
url: ""
